FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o recommendation-service .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/recommendation-service .
EXPOSE 5000
CMD ["./recommendation-service"]
