FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

COPY src ./src
COPY prisma ./prisma
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

RUN npx prisma generate
RUN npm run build

ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "run", "start:prod"]