FROM python:3.13-slim

WORKDIR /

COPY requirements.txt /

RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install "fastapi[standard]"

COPY . .

EXPOSE 8000

CMD ["fastapi", "dev", "main.py"]